### ISSUE TITLE
Schema (draft)

### ISSUE THREAD

**Issue by mfmeier** [Blaque-Majick/02-29-pair-project#2]
DB.define_table("users")
DB.define_column("users","name","string")
DB.define_column("users","email","string")
DB.define_column("users","password","string")

DB.define_table("exceptions")
DB.define_column("exceptions","error_name","string")
DB.define_column("exceptions","error_description","string")
DB.define_column("exceptions","error_suggestion","string")

DB.define_table("histories")
DB.define_column("histories","user_id","integer")
DB.define_column("histories","error_history","string")
DB.define_column("histories","error_suggestion","string")

**Comment by sumeetjain** [comment]
You might have a problem calling the table 'exceptions', because `Exception` is an actual class in Ruby already. Consider `encounters` or `errors` or something like that instead.

Your app won't really give suggestions. It's just going to identify some information about each error that's encountered. So I suggest removing the `error_suggestion` column. We're not really sure yet what kind of information we'll be returning to people, and that's okay for now.

`error_description` should be `text` instead of `string`, because it might be a lot of text (and `string` is for small amounts).

You can remove the `histories` table. Just add a `user_id` column to the `encounters` table.

**Comment by mfmeier** [comment]
DB.define_table("users")
DB.define_column("users","name","string")
DB.define_column("users","email","string")
DB.define_column("users","password","string")

DB.define_table("errors")
DB.define_column("errors","error_name","string")
DB.define_column("errors","error_description","text")
DB.define_column("errors","user_id","string")
